config/routes.rb
Rails.application.routes.draw do
  resources :groups
  resources :group_memberships
  resource :user_session
  resources :users
  resources :games do
    resources :scores
  end

  root 'welcome#index'

  get '/about', :to => 'welcome#about', as: 'about'
  get '/scores', :to => 'scores#index', as: 'scores'

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :scores

  def top_scores
    scores.where(game_id: id).order(:amount).reverse.first(10)
  end

  def image_name
    name.downcase.tr(" ", "_").gsub(/[^0-9a-z_ ]/i, '')
  end
end

app/models/group.rb
class Group < ActiveRecord::Base

  has_many :users, through: :group_memberships
  has_many :group_memberships
  has_many :scores

  def commissioner
    group_memberships.where(commissioner: true).first.user
  end

  def member(user)
    group_memberships.where(member_id: user.id).present?
  end
end

app/models/group_membership.rb
class GroupMembership < ActiveRecord::Base
  belongs_to :user
  belongs_to :group

  validates :user, uniqueness: { scope: :group }
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/models/score.rb
class Score < ActiveRecord::Base
  belongs_to :game
  belongs_to :user
  belongs_to :group

  validates :game, presence: true
  validates :user, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :roles
  acts_as_authentic

  has_many :scores
  has_many :games, through: :scores
  has_many :groups, through: :group_memberships
  has_many :group_memberships

  def member_of(group)
    group_memberships.where(group_id: group.id).present?
  end

  def role_symbols
    (roles || []).map {|r| r.title.to_sym}
  end

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  # configuration here, see documentation for sub modules of Authlogic::Session
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception
  helper_method :current_user_session, :current_user

  def current_user_session
    return @current_user_session if defined?(@current_user_session)
    @current_user_session = UserSession.find
  end

  def current_user
    return @current_user if defined?(@current_user)
    @current_user = current_user_session && current_user_session.record
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
      @games = Game.all
    end

    def show
      @game = Game.find(params[:id])
    end

    def new
      @game = Game.new
    end

    def edit
      @game = Game.find(params[:id])
      render 'new'
    end

    def create
      @game = Game.new(game_params)
      if @game.save
        redirect_to @game
      else
        render 'new'
      end
    end

    def update
      @game = Game.find(params[:id])
      if @game.update(game_params)
        flash.now[:notice] = "Your List was updated!"
        redirect_to @game
      else
        render 'new'
      end
    end

    private

    def game_params
      params.require(:game).permit(:name, :description)
    end
end

app/controllers/group_memberships_controller.rb
class GroupMembershipsController < ApplicationController
  def create
    @group_membership = GroupMembership.new(group_memberships_params)
    if @group_membership.save
      redirect_to @group_membership.group
    else
      flash.now[:notice] = "You failed to join the group"
      redirect_to @group_membership.group
    end
  end

  def update
    @group_membership = GroupMembership.find(params[:id])
    if @group_membership.update(group_memberships_params)
      flash.now[:notice] = "Your List was updated!"
      redirect_to @group_membership.group
    else
      flash.now[:notice] = "You failed to update the membership"
      redirect_to @group_membership.group
    end
  end

  private

  def group_memberships_params
    params.require(:group_membership).permit(:group_id, :user_id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
    @members = @group.users
    @group_membership = GroupMembership.new
  end

  def new
    @group = Group.new
  end

  def edit
    @group = Group.new
    render 'new'
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      GroupMembership.create(group_id: @group.id, user_id: current_user.id, commissioner: true)
      redirect_to @group
    else
      render 'new'
    end
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      flash.now[:notice] = "Your List was updated!"
      redirect_to @group
    else
      render 'new'
    end
  end

  private

  def group_params
    params.require(:group).permit(:name)
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  def index
    @games = Game.all
  end

  def show
    @score = Score.find(params[:id])
  end

  def new
    @score = Score.new
    @score.game_id = params[:game_id]
  end

  def edit
    @score = Score.new
    render 'new'
  end

  def create
    @score = Score.new(score_params)
    if @score.save
      redirect_to game_path(@score.game)
    else
      render 'new'
    end
  end

  def update
    @score = Score.find(params[:id])
    if @score.update(score_params)
      flash.now[:notice] = "Your List was updated!"
      redirect_to game_path(@score.game)
    else
      render 'new'
    end
  end

  private

  def score_params
    params.require(:score).permit(:game_id, :user_id, :amount)
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      flash[:notice] = "Login successful!"
      redirect_to root_path
    else
      render :action => :new
    end
  end

  def destroy
    current_user_session.destroy
    flash[:notice] = "Logout successful!"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Account registered!"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def show
    @user = current_user
  end

  def edit
    @user = User.find(params[:id])
    render 'new'
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:notice] = "Account updated!"
      redirect_to user_path(@user)
    else
      render :action => :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:password, :password_confirmation, :email, :name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @games = Game.all.first(6)
    current_user ? @groups = current_user.groups : @groups = Group.all
  end

  def about
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message
            end)
    end
    nil
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/group_memberships_helper.rb
module GroupMembershipsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/user_session_helper.rb
module UserSessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/games/index.html.erb
<div id="fh5co-our-services" data-section="games">
  <div class="container">
    <%= link_to "New Group", new_group_path, html_options = {class: "btn btn_success"} if permitted_to?(:create, :games) %>
    <div class="row row-bottom-padded-sm">
      <div class="col-md-12 section-heading text-center">
        <h2 class="to-animate">Games</h2>
        <div class="row">
          <div class="col-md-8 col-md-offset-2 to-animate">
            <h3>Old Computer Games Couldn’t Be Won. They Just Got Harder and Faster Until You Died. Just Like Real Life</h3>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <% @games.each do |g| %>
        <%= link_to g do %>
        <div class="col-md-4">
          <div class="box to-animate">
		  <div class="col-sm-12"><span><%= image_tag(g.image_name, width: "100%" ) %></span></div>
            <h3><%=g.name%></h3>
          </div>
        </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/games/new.html.erb
<div class="container padding-top-50 default-background-color">
  <%= bootstrap_form_for(@game) do |f| %>
    <%= f.text_field :name %>
    <%= f.text_field :description %>
    <%= f.submit "Create Game" %>
  <% end %>
</div>

app/views/games/show.html.erb
<div class="container padding-top-50">
  <h3><%= @game.name %></h3>
  <p><%= @game.description %></p>  
  <p><%= link_to "New Score", new_game_score_path(@game), class: "btn btn-primary" if current_user %></p>
</div>

app/views/groups/index.html.erb
<div id="fh5co-our-services" data-section="groups">
  <div class="container">
    <div class="row row-bottom-padded-sm">
      <div class="col-md-12 section-heading text-center">
        <h2 class="to-animate">Groups</h2>
        <div class="row">
          <div class="col-md-8 col-md-offset-2 to-animate">
            <h3>Its dangerous to go alone. Join a group!</h3>
          </div>
        </div>
      </div>
    </div>
    <% if current_user %>
      <%= link_to new_group_path do %>
        <div class="col-md-4">
          <div class="box to-animate">
            <div class="icon colored-1"><span><i class="icon-mustache"></i></span></div>
            <h3>New Group</h3>
            <p></p>
          </div>
        </div>
      <% end %>
    <% end %>
    <% @groups.each do |g| %>
      <%= link_to g do %>
      <div class="col-md-4">
        <div class="box to-animate">
          <div class="icon colored-1"><span><i class="icon-mustache"></i></span></div>
          <h3><%=g.name%></h3>
          <ul>
            <% g.group_memberships.each do |gm| %>
              <%= gm.user.name %>
            <% end %>
          </ul>
        </div>
      </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/groups/new.html.erb
<div class="container padding-top-50 default-background-color">
  <%= bootstrap_form_for(@group) do |f| %>
    <%= f.text_field :name %>
    <%= f.submit "Create Group" %>
  <% end %>
</div>

app/views/groups/show.html.erb
<div class="container padding-top-50">
  <h3><%= @group.name %></h3>
  <h5>Commissioner: <%= @group.commissioner.name %></h5>
  <h5>Users</h5>
  <ul class="member_list">
    <% @members.each do |m| %>
      <li><%= m.name %></li>
    <% end %>
  </ul>
  <% if current_user && !current_user.member_of(@group) %>
    <%= bootstrap_form_for @group_membership do |f| %>
      <%= f.hidden_field :group_id, :value => @group.id %>
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <%= f.submit "Join Group" %>
    <% end %>
  <% end %>
</div>

app/views/scores/index.html.erb
<div id="slider" data-section="home">
   <div class="owl-carousel owl-carousel-fullwidth">
    <!-- You may change the background color here. -->
    <% @games.each do |g| %>
      <div class="item" style="background: #352f44;">
        <div class="container" style="position: relative;">
          <div class="row">
            <div class="fh5co-owl-text-wrap">
              <div class="fh5co-owl-text">
                <h1 class="fh5co-lead to-animate"><%= g.name %></h1>
                <div class="fh5co-sub-lead to-animate-2">
                  <% g.top_scores.each_with_index do |s, i| %>
                  <div class="col-lg-offset-3 col-lg-3 col-md-offset-3 col-md-3 col-sm-offset-3 col-sm-3 col-xs-4 col-xs-offset-0"><%= i+1  %></div>
                  <div class="col-lg-3 col-md-3 col-sm-3  col-xs-4"><%= s.user.name %></div>
                  <div class="col-lg-3 col-md-3 col-sm-3  col-xs-4"><%= s.amount %></div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

app/views/scores/new.html.erb
<div class="container padding-top-50">
  <%= bootstrap_form_for @score, url: game_scores_path do |f| %>
    <%= f.collection_select(:game_id, Game.all, :id, :name, { include_blank:true}) %>
    <%= f.number_field :amount %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.submit "Add New Score" %>
  <% end %>
</div>

app/views/scores/show.html.erb
<div class="container padding-top-50">
  <h3><%= @score.game.name %></h3>
  <p><%= @score.amount %></p>
  <p><%= link_to "New Score", new_game_score_path(game_id:@game.id), class: "btn btn-primary" %></p>
</div>

app/views/user_sessions/new.html.erb
<div class="container padding-top-50">
  <h1>Login</h1>

  <%= form_for @user_session, :url => user_session_path do |f| %>
    <%= f.label :email %><br />
    <%= f.text_field :email %><br />
    <br />
    <%= f.label :password %><br />
    <%= f.password_field :password %><br />
    <br />
    <%= f.check_box :remember_me %><%= f.label :remember_me %><br />
    <br />
    <%= f.submit "Login" %>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="container padding-top-50">
<h1>Register</h1>

<%= form_for @user do |f| %>
  <%= f.label :email %><br>
  <%= f.text_field :email %><br>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <%= f.label :password %><br>
  <%= f.password_field :password %><br>
  <%= f.label :password_confirmation %><br>
  <%= f.password_field :password_confirmation %><br>
  <%= f.submit "Register" %>
<% end %>

app/views/users/show.html.erb
<div class="container padding-top-50">
  <h3><%= @user.email %></h3>
</div>