config/routes.rb
Rails.application.routes.draw do
  resources :groups
  resources :group_memberships
  resource :user_session
  resources :users
  resources :games do
    resources :scores
  end

  root 'welcome#index'

  get '/about', :to => 'welcome#about', as: 'about'
  get '/scores', :to => 'scores#index', as: 'scores'

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :scores

  def top_scores
    scores.where(game_id: id).order(:amount).reverse.first(10)
  end

  def image_name
    name.downcase.tr(" ", "_").gsub(/[^0-9a-z_ ]/i, '')
  end
end

app/models/group.rb
class Group < ActiveRecord::Base

  has_many :users, through: :group_memberships
  has_many :group_memberships
  has_many :scores

  def commissioner
    group_memberships.where(commissioner: true).first.user
  end

  def member(user)
    group_memberships.where(member_id: user.id).present?
  end
end

app/models/group_membership.rb
class GroupMembership < ActiveRecord::Base
  belongs_to :user
  belongs_to :group

  validates :user, uniqueness: { scope: :group }
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/models/score.rb
class Score < ActiveRecord::Base
  belongs_to :game
  belongs_to :user
  belongs_to :group

  validates :game, presence: true
  validates :user, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :roles
  acts_as_authentic

  has_many :scores
  has_many :games, through: :scores
  has_many :groups, through: :group_memberships
  has_many :group_memberships

  def member_of(group)
    group_memberships.where(group_id: group.id).present?
  end

  def role_symbols
    (roles || []).map {|r| r.title.to_sym}
  end

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  # configuration here, see documentation for sub modules of Authlogic::Session
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
      @games = Game.all
    end

    def show
      @game = Game.find(params[:id])
    end

    def new
      @game = Game.new
    end

    def edit
      @game = Game.find(params[:id])
      render 'new'
    end

    def create
      @game = Game.new(game_params)
      if @game.save
        redirect_to @game
      else
        render 'new'
      end
    end

    def update
      @game = Game.find(params[:id])
      if @game.update(game_params)
        flash.now[:notice] = "Your List was updated!"
        redirect_to @game
      else
        render 'new'
      end
    end

    private

    def game_params
      params.require(:game).permit(:name, :description)
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
    @members = @group.users
    @group_membership = GroupMembership.new
  end

  def new
    @group = Group.new
  end

  def edit
    @group = Group.new
    render 'new'
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      GroupMembership.create(group_id: @group.id, user_id: current_user.id, commissioner: true)
      redirect_to @group
    else
      render 'new'
    end
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      flash.now[:notice] = "Your List was updated!"
      redirect_to @group
    else
      render 'new'
    end
  end

  private

  def group_params
    params.require(:group).permit(:name)
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  def index
    @games = Game.all
  end

  def show
    @score = Score.find(params[:id])
  end

  def new
    @score = Score.new
    @score.game_id = params[:game_id]
  end

  def edit
    @score = Score.new
    render 'new'
  end

  def create
    @score = Score.new(score_params)
    if @score.save
      redirect_to game_path(@score.game)
    else
      render 'new'
    end
  end

  def update
    @score = Score.find(params[:id])
    if @score.update(score_params)
      flash.now[:notice] = "Your List was updated!"
      redirect_to game_path(@score.game)
    else
      render 'new'
    end
  end

  private

  def score_params
    params.require(:score).permit(:game_id, :user_id, :amount)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Account registered!"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def show
    @user = current_user
  end

  def edit
    @user = User.find(params[:id])
    render 'new'
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:notice] = "Account updated!"
      redirect_to user_path(@user)
    else
      render :action => :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:password, :password_confirmation, :email, :name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @games = Game.all.first(6)
    current_user ? @groups = current_user.groups : @groups = Group.all
  end

  def about
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message
            end)
    end
    nil
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/group_memberships_helper.rb
module GroupMembershipsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/user_session_helper.rb
module UserSessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>TappersScoreBoard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


  <!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
	<link rel="shortcut icon" href="favicon.ico">

	/* For demo purpose only */

	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="js/respond.min.js"></script>
	<![endif]-->

	</head>
	<body>
	<header role="banner" id="fh5co-header">
			<div class="container">
				<!-- <div class="row"> -->
			    <nav class="navbar navbar-default">
		        <div class="navbar-header">
		        	<!-- Mobile Toggle Menu Button -->
					<a href="#" class="js-fh5co-nav-toggle fh5co-nav-toggle" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"><i></i></a>
								<a href="<%=root_url%>" class="navbar-brand" data-nav-section="home">Home</a>
		        </div>
		        <div id="navbar" class="navbar-collapse collapse">
		          <ul class="nav navbar-nav navbar-right">
			            <li><%= link_to "Games", games_path %></li>
				    <li><%= link_to "Scores", scores_path %></li>
				    <li><%= link_to "Groups", groups_path%></li>
				    <li><%= link_to "About", about_path%></li>
								<% if current_user %>
									<li><%= link_to "Log Out", user_session_path, :method => :delete %></li>
								<% else %>
									<li><%= link_to "Log In", new_user_session_path %></li>
									<li><%= link_to "Sign Up", new_user_path %></li>
								<% end %>
		          </ul>
		        </div>
			    </nav>
			  <!-- </div> -->
		  </div>
	</header>
	<% if flash[:notice] %>
		<div class="container padding-top-50">
	    <div class="notice"><%= flash[:notice] %></div>
		</div>
	<% end %>
	<%= yield %>


	<footer id="footer" role="contentinfo">
		<div class="container">
			<div class="row row-bottom-padded-sm">
				<div class="col-md-12">
					<p class="copyright text-center">Created 2016 <a href="http://www.matthewjfair.com/"> by Matt Fair</a>. <br> Inspired by <a href="http://tappersarcadebar.com/" target="_blank">Tappers Arcade Bar</a></p>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12 text-center">
          <ul class="social social-circle">
            <li><a href="https://twitter.com/Matt_Fair_86"><i class="icon-twitter"></i></a></li>
            <li><a href="#"><i class="icon-linkedin"></i></a></li>
            <li><a href="http://www.matthewjfair.com"><i class="icon-screen-desktop"></i></a></li>
          </ul>
				</div>
			</div>
		</div>
	</footer>

	</body>
</html>